### ISSUE TITLE
SYNOPSIS stuff messes up formatting

### ISSUE THREAD

**Issue by zoffixznet** [zoffixznet/Dist-Zilla-Plugin-Pod-Spiffy#10]
![zq2zxjt](https://cloud.githubusercontent.com/assets/5747918/11610673/dabc66f2-9b78-11e5-8014-e090dab4fea1.png)

**Comment by shlomif** [comment]
This seems fine now in firefox on https://metacpan.org/pod/Mew . Can this bug be closed? This is part of the CPAM PRC.
